FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3-pydantic \
        python3-urllib3  \
        python3-yaml  \
        python3-requests  \
        python3-typing-extensions \
    && rm -Rf /var/lib/apt/lists/*

COPY get.py /

ENTRYPOINT ["/usr/bin/env", "python3", "get.py"]
