FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3-venv \
    && rm -Rf /var/lib/apt/lists/*

COPY get.py /
COPY requirements.txt /

RUN python3 -m venv .venv \
    && .venv/bin/pip3 install -r requirements.txt

ENTRYPOINT [".venv/bin/python3", "get.py"]
